### ISSUE TITLE
Does not work with Angular 9

### ISSUE THREAD

**Issue by RafaelLiendo** [fals/ng2-brpipes#12]
![image](https://user-images.githubusercontent.com/12666898/77402950-37f7ed00-6d8e-11ea-95ec-5f54fcd544f6.png)

Solved ass soon as the PR #13 get approved

**Comment by fals** [comment]
@RafaelLiendo CI is running lets see if we have a new package soon :)

**Comment by fals** [comment]
The new version of the package was pushed. A minor issue with the karma.config.js. You need to set singleRun: true, otherwise CircleCI hangs forever. Thank you @RafaelLiendo :)

**Comment by RafaelLiendo** [comment]
\o/ yay it worked!
