### ISSUE TITLE
Uso de máscaras

### ISSUE THREAD

**Issue by dayanfcosta** [fals/ng2-brpipes#3]
Acho que seria viável a implementação de máscaras junto aos pipes, pois nos testes em que realizei, o mesmo não barrava a quantidade de caractéres do CEP, por exemplo. O que fiz foi aplicar algumas diretivas de filtros tanto pra CEP, CPF e CNPJ, se quiser posso estar passando-as para incorporá-las ao projeto, deixando-o mais rico.

**Comment by dayanfcosta** [comment]
Na verdade o ideal seria barrar a quantidade de caractéres digitada pelo usuário, no caso como eu tinha uma diretiva já pronta eu só apliquei ela, mas posso estar disponibilizando o código da mesma para que esteja aprimorando os pipes com este recurso

**Comment by fals** [comment]
@dayanfcosta Só estou vendo agora seu issue! A função do pipe é transformar uma entrada em algo formatado. Acho que não é responsabilidade dele validar, como você mesmo disse, existem diretivas exatamente para isso. Se a entrada do pipe não está no formato correto, há uma inconsistência nos dados que você tem, não no Pipe. Se você olhar de perto os pipes do próprio framework ele descarta datas, que não são data e ignora o valor incorreto, por exemplo.
