### ISSUE TITLE
Bug ao usar o backspace

### ISSUE THREAD

**Issue by renanss** [fals/ng2-brpipes#4]
Quando tento apagar os numeros do telefone, aparece um monte de parenteses. 
![image](https://user-images.githubusercontent.com/13458004/33185727-c1872ac6-d06b-11e7-9503-47d9caf61153.png)

Implementei desta forma:
`      <input type="tel" class="form-control custom-input" [ngModel]="formData.tel | telefone" name="number" (ngModelChange)="formData.tel= $event" required="required">
`

**Comment by fals** [comment]
@renanss desculpe a demora não estou recebendo as notificações. Vou analisar o problema com calma, pois não foi testado com bind.

**Comment by fals** [comment]
@renanss pode ser que não resolva totalmente o problema, campos que você digita qualquer coisa podem continuar com o problema, por favor atualizar para nova versão
